export const brandContent = {
  eyebrow: 'IMAGINE BEYOND',
  caption: 'CREATIVE AI STUDIO',
  title: 'CREAI App Directory',
  subtitle:
    'A living home for CREAI products, experiments, and internal launches across AI, interface design, and modern app systems.',
  socialLinks: [
    { label: 'Instagram', url: 'https://www.instagram.com/creainetwork/' },
    { label: 'X', url: 'https://x.com/creainetwork' },
  ],
}

export const appCategories = [
  'All',
  'AI Workspace',
  'Productivity',
  'Internal Tool',
  'Client Experience',
  'Prototype',
]

export const seedApps = [
  {
    id: 'signal-deck',
    name: 'Signal Deck',
    slug: 'signal-deck',
    category: 'AI Workspace',
    status: 'Live',
    summary: 'An AI strategy board for collecting ideas, prompts, and launch directions in one visual workspace.',
    audience: 'Internal',
    updatedAt: '2026-03-25',
    url: '#',
    featured: true,
    accent: '#c2ff29',
    published: true,
    stacks: ['Supabase', 'React', 'Prompt Systems', 'Internal Ops'],
    socialLinks: [
      { label: 'Website', url: '#' },
      { label: 'X', url: 'https://x.com/creainetwork' },
    ],
    storeLinks: [
      { label: 'Web App', url: '#' },
      { label: 'App Store', url: '#' },
    ],
  },
  {
    id: 'brief-forge',
    name: 'Brief Forge',
    slug: 'brief-forge',
    category: 'Client Experience',
    status: 'Beta',
    summary: 'Turns raw client notes into structured product briefs, UI scopes, and action items.',
    audience: 'Client-facing',
    updatedAt: '2026-03-22',
    url: '#',
    featured: false,
    accent: '#9adf5b',
    published: true,
    stacks: ['React', 'Design Systems', 'AI Briefing', 'Client Workflow'],
    socialLinks: [{ label: 'Instagram', url: 'https://www.instagram.com/creainetwork/' }],
    storeLinks: [{ label: 'Web App', url: '#' }],
  },
  {
    id: 'canvas-ops',
    name: 'Canvas Ops',
    slug: 'canvas-ops',
    category: 'Internal Tool',
    status: 'Internal',
    summary: 'A lightweight operations dashboard for tracking launches, owners, and production readiness.',
    audience: 'Studio',
    updatedAt: '2026-03-19',
    url: '#',
    featured: false,
    accent: '#b8ff7d',
    published: true,
    stacks: ['Dashboarding', 'Operations', 'Internal Tracking'],
    socialLinks: [],
    storeLinks: [],
  },
  {
    id: 'pulse-room',
    name: 'Pulse Room',
    slug: 'pulse-room',
    category: 'Prototype',
    status: 'Concept',
    summary: 'An experimental interface for browsing AI-native product concepts in an editorial way.',
    audience: 'Public',
    updatedAt: '2026-03-17',
    url: '#',
    featured: false,
    accent: '#8fd14f',
    published: false,
    stacks: ['Prototype', 'Editorial UI', 'Exploration'],
    socialLinks: [],
    storeLinks: [],
  },
]
